name: Build & Test
on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: cd app ; npm install

      - name: Run tests
        run: cd app ; npm run test